name: gh-counter

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  gh-counter:
    uses: kitsuyui/gh-actions-workflows/.github/workflows/gh-counter.yml@88f48ad6844fb6c902ec82614c9ca54d91551d25 # main
